[browser] Add PermissionPage. JB#50492
sailfishos/sailfish-browser pull request #694
Opened 2020-08-09 15:35 UTC by atatarov

2020-08-13 15:07 UTC, llewelld commented on src/pages/components/PermissionPage.qml
> +            //% "Cookie"
"Cookies" plural rather than "Cookie" singular would make more sense.

2020-09-03 12:36 UTC, atatarov commented on src/pages/components/PermissionListPage.qml
> +        }
We need "Dialogs" to work with prompt

2020-09-10 16:00 UTC, llewelld requested changes

2020-09-10 16:29 UTC, llewelld commented on src/pages/components/PermissionListPage.qml
> +        permissionType: filterType
Thanks; this is now fixed.

2020-09-10 16:32 UTC, llewelld approved these changes

2020-10-28 07:58 UTC, rainemak commented
This must be superseded by https://github.com/sailfishos/sailfish-browser/pull/725. Please close.

2020-10-28 08:22 UTC, closed without merging