[sailfish-browser] Add secondaryBarHeight to overlay. Contribures to JB#51715
sailfishos/sailfish-browser pull request #729
Opened 2020-10-29 16:29 UTC by atatarov

2020-11-02 20:04 UTC, okodron approved these changes

2020-11-03 12:38 UTC, paveltkv approved these changes

2020-11-03 15:23 UTC, rainemak commented
This causes odd looking flickering and change to the host that is visible in the toolbar all the time.

Reason for that is (as far as my eye can spot if) when opening secondary layer it's now animating from to bottom... not from from the top of the first row.

2020-11-03 15:25 UTC, rainemak requested changes
Let's fix that flickering before merging.

2020-11-03 17:27 UTC, rainemak requested changes
Almost there...

Please change CaptivePortalToolBar.qml as well...

```
    readonly property real rowHeight: height
    readonly property int maxRowCount: 1
```
There we have higher row => let's keep to API in sync that OverlayAnimator keeps on working.

2020-11-03 17:36 UTC, rainemak reviewed
More comments.

2020-11-03 17:36 UTC, rainemak commented on src/pages/components/CaptivePortalToolBar.qml
> +    readonly property real rowHeight: height
```
readonly property int maxRowCount: 1
```
This is still missing... Please also rebase.

2020-11-03 17:40 UTC, rainemak approved these changes
:+1:

2020-11-03 17:40 UTC, merged