[sailfish-browser] Notify EmbedLite view when virtual keyboard is opened. Contributes to JB#51962
sailfishos/sailfish-browser pull request #741
Opened 2020-11-16 17:45 UTC by paveltkv

2020-11-17 10:24 UTC, rainemak commented on src/qtmozembed/declarativewebpage.cpp
> +void DeclarativeWebPage::setVirtualKeyboardOpened(bool opened)
Could you push all this down to the QtMozEmbed.

2021-05-21 14:32 UTC, rainemak commented on apps/browser/qml/pages/BrowserPage.qml
> +                                       : 0
```
virtualKeyboardHeight: virtualKeyboardObserver.panelSize
```
See when condition. Further, given that virtualKeyboardHeight works is it should you should remove virtualKeyboardMargin (setting margin as well) + cleanup related sendVkbOpenCompositionMetrics from browser side and "embedui:vkbOpenCompositionMetrics" handling from the embedlite-components

2021-05-21 14:33 UTC, rainemak commented on apps/captiveportal/qml/pages/CaptivePortalPage.qml
> +                virtualKeyboardHeight: virtualKeyboardObserver.opened
Same as above

2021-05-21 14:33 UTC, rainemak requested changes
Please cleanup virtualKeyboardMargin and related code that will obsoleted once it is removed.

2021-05-27 11:52 UTC, llewelld approved these changes
This looks good to me and works nicely. It's also an important improvement for the browser, so really nice to have.

I think at this stage it might be better to combine #733 and #741 into one (possibly two) commits. Otherwise you have code added/changed that gets immediately removed.

2021-05-27 12:13 UTC, rainemak commented on apps/captiveportal/qml/pages/CaptivePortalPage.qml
> +                virtualKeyboardHeight: virtualKeyboardObserver.imSize
Need to check in more detail but we should not use the value that is animated -- only one single update and that's it.

2021-06-01 08:56 UTC, rainemak commented on apps/qtmozembed/declarativewebpage.cpp
This doesn't build now...

See DeclarativeWebPage::updateViewMargins() and m_virtualKeyboardMargin. Just change to use virtualKeyboardHeight().

2021-06-01 09:28 UTC, rainemak requested changes
See one build error. After that is fixed, let's get this one merged.

2021-06-01 09:30 UTC, rainemak commented on apps/captiveportal/qml/pages/CaptivePortalPage.qml
> +                virtualKeyboardHeight: virtualKeyboardObserver.imSize
This is good.

2021-06-01 16:31 UTC, paveltkv commented
Rebased, combined with #733 and removed margin change animation.

2021-06-02 12:21 UTC, llewelld approved these changes
This looks good to me, thank you Pavel. In testing it worked nicely, no glitches or obvious performance issues. The code looks good too. Re-approving

2021-06-03 07:18 UTC, rainemak commented
> This looks good to me and works nicely. It's also an important improvement for the browser, so really nice to have.
> 
I do agree with this comment. Also worth saying that more testing we get for this, sooner we find the issues and have them fixed.

2021-06-03 07:18 UTC, rainemak approved these changes
Looks good now and works well! Thanks @paveltkv

2021-06-03 07:52 UTC, okodron approved these changes

2021-06-03 09:17 UTC, merged