[sailfish-browser] Only save working pages to the history. Fixes JB#2…
sailfishos/sailfish-browser pull request #807
Opened 2021-03-16 13:52 UTC by mkenttala

…0436

2021-03-18 11:07 UTC, rainemak requested changes
Please give a look to the review comments. There are some issues that need to be addresses before this can be landed.

2021-03-18 11:35 UTC, mkenttala commented on apps/qtmozembed/declarativewebpage.h
> +    void contentLoaded();
domContentLoaded is not useful in this case because it's sent even when page fails.

2021-03-18 12:53 UTC, rainemak commented on apps/qtmozembed/declarativewebpage.h
> +    void contentLoaded();
But for instance in case of invalid url (server not found) argument is about:neterror from which we can know that this was an error.

2021-03-18 13:01 UTC, rainemak commented on apps/qtmozembed/declarativewebpage.h
> +    void contentLoaded();
The error state could actually go to the qtmozembed and qmozview

2021-03-19 11:06 UTC, rainemak commented on apps/qtmozembed/declarativewebpage.h
> +    void contentLoaded();
That would actually imply that domContentLoaded signal should be moved to the qtmozembed as well.

2021-03-19 16:43 UTC, mkenttala commented
New version with some of the review comments addressed. Handling every possible way to load (and fail) a page proved quite difficult so there might be some holes left.

2021-03-23 15:57 UTC, rainemak requested changes
There's one bigger issue and that's the fact that a tab might disappear after browser restart. Proposed solution on a comment.

2021-03-24 13:26 UTC, mkenttala commented on apps/qtmozembed/declarativewebpage.cpp
> +    if (!m_domContentLoaded && m_urlReady) {
This gets called multiple times even when the url() is still the old one, not the url currently loading. Just waiting for the proper url.

2021-03-24 13:28 UTC, mkenttala commented on apps/history/declarativetabmodel.cpp
> +            createTab(m_tabs.at(index));
Yep, now just adding to the history database if page load is ok, tab history remains.

2021-03-25 12:17 UTC, rainemak reviewed
Another round.

2021-03-29 07:05 UTC, rainemak commented on apps/history/declarativehistorymodel.cpp
> +    beginInsertRows(QModelIndex(), 0, 1);
No need start model row insert here... search will query new set of history entries from database and sorting is handled by `updateModel`.

Just adding should be enough. There's no really means to checking history entries without  entering a search term.

2021-03-29 07:06 UTC, rainemak commented on apps/core/declarativewebcontainer.h
> +    DeclarativeHistoryModel *historyModel();
```suggestion
    DeclarativeHistoryModel *historyModel() const;
```

2021-03-29 07:08 UTC, rainemak commented on apps/core/declarativewebcontainer.h
> +    Q_PROPERTY(DeclarativeHistoryModel* historyModel READ historyModel WRITE setHistoryModel)
NOTIFY signal missing

2021-03-29 14:49 UTC, rainemak commented on apps/history/declarativehistorymodel.cpp
> +    int id = DBManager::instance()->addHistoryEntry(url, title, time);
I meant this single line should be enough. When you start typing to the search field, model updates on every single character and dbworker emits historyAvailable.

Problem with this approach is that appending to the end can be wrong place as sorting comes from dbworker. It should be inserted to the right place if any. Hence, I'd not add anything extra here rather just call addHistoryEntry(...).

If you think that's worth to update model here, you could store current search term to member variable (see search) and call search(m_searchTerm);

2021-03-29 14:53 UTC, rainemak commented on apps/core/declarativewebcontainer.cpp
> +            });
This same should be done for the title change. Sounds that update(url, title) would be good for that.

2021-03-30 05:42 UTC, rainemak commented on apps/core/declarativewebcontainer.cpp
> +            });
Already handled by the historymodel itself.

2021-03-30 05:48 UTC, rainemak commented on apps/history/declarativehistorymodel.cpp
> +** Copyright (C) 2021 Jolla Ltd.
```suggestion
** Copyright (c) 2013 - 2021 Jolla Ltd.
```

2021-03-30 05:48 UTC, rainemak commented on apps/history/declarativehistorymodel.cpp
> +** Copyright (C) 2021 Jolla Ltd.
Apply similar update for other changed files as well.

2021-03-31 05:46 UTC, rainemak approved these changes
Thanks Marko for pushing this through!

2021-03-31 07:04 UTC, merged