[sailfish-browser] Add PopupBlockerDialog. Contributes to JB#52731
sailfishos/sailfish-browser pull request #815
Opened 2021-03-20 14:24 UTC by atatarov

We want to notify the user when pop-ups are blocked.
Handling embed:popupblocked allows to get these events.

2021-04-08 17:08 UTC, llewelld requested changes
This is working nicely. There are a few things worth considering I've added as comments, and it looks like translation generation needs to be hooked up still as well.

2021-04-08 17:08 UTC, llewelld commented on apps/shared/PopupBlockedDialog.qml
> +            //% "We have prevented %1 from opening pop-up window. Would you like to able this website open pop-ups?"
A suggested re-wording:
"The site %1 has requested to open a new tab. Would you like to allow it to open new tabs?"

2021-04-08 17:08 UTC, llewelld commented on apps/shared/PopupBlockedDialog.qml
> +        }
I wonder if something like the following should also be added?
"You can change this setting in future by selecting the padlock icon in the toolbar, or from the Permissions page in Settings"

2021-04-08 17:08 UTC, llewelld commented on apps/shared/PopupBlockedDialog.qml
> +            PermissionManager.add(dialog.host, "popup", PermissionManager.Allow, PermissionManager.Session)
One thing I find a little confusing is that the Permissions list doesn't distinguish between "Session allow" and "Always allow" permissions. Is this something that could or should be included?

2021-04-09 07:37 UTC, sledges commented on apps/browser/qml/pages/PrivacySettingsPage.qml
> +                title: qsTrId("sailfish_browser-he-privacy-settings")
We have translation backup and will be able to restore, it's not uncommon. I'll keep an eye on when this should happen after this PR is merged.

2021-04-09 07:40 UTC, llewelld commented on apps/browser/qml/pages/PrivacySettingsPage.qml
> +                title: qsTrId("sailfish_browser-he-privacy-settings")
Great, thank you @sledges. And no need to alter your PR here in that case @atatarov.

2021-04-21 16:37 UTC, llewelld requested changes
One very small change requested, but this looks fine to me otherwise.

The following will also be needed to ensure lupdate gets run on the files with the new translation strings: https://github.com/sailfishos/sailfish-browser/pull/829

2021-04-22 11:48 UTC, llewelld commented on apps/shared/PopupBlockedDialog.qml
> +****************************************************************************/
Fixed with https://github.com/sailfishos/sailfish-browser/pull/829

2021-04-22 11:48 UTC, llewelld approved these changes
LGTM

2021-04-22 12:02 UTC, xlise commented
Maybe add dependency embedlite-components version 1.22.29 "embed:popupblocked"

2021-04-22 12:30 UTC, okodron approved these changes

2021-04-28 10:52 UTC, atatarov commented
> Maybe add dependency embedlite-components version 1.22.29 "embed:popupblocked"

It depends of sailfish-components-webview, but there is no dependencies of embedlite. It doesn't crash the browser and I think it could be missed

2021-04-28 12:06 UTC, xlise commented
LGTM

2021-04-28 12:24 UTC, okodron approved these changes

2021-04-30 07:47 UTC, llewelld approved these changes
Still LGTM.

2021-04-30 07:48 UTC, merged